/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlRouteImport } from './routes/$url'
import { Route as IndexRouteImport } from './routes/index'

const UrlRoute = UrlRouteImport.update({
  id: '/$url',
  path: '/$url',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$url': typeof UrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$url'
  id: '__root__' | '/' | '/$url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UrlRoute: typeof UrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$url': {
      id: '/$url'
      path: '/$url'
      fullPath: '/$url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UrlRoute: UrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
